# QR decomposition

In [24]:
import numpy.linalg as nla

In [25]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])

In [26]:
Q = nla.qr(A)[0]
R = nla.qr(A)[1]

In [27]:
print(Q)
print(R)

[[-0.29986176 -0.45548197  0.72189882 -0.4260061 ]
 [-0.39687586 -0.16662497  0.24300203  0.86929609]
 [-0.81403649 -0.07202495 -0.52451613 -0.23883014]
 [-0.29986176  0.87154157  0.38038788 -0.07617926]]
[[-1.13385581 -0.36099828 -2.95099251  1.01071052]
 [ 0.         -0.64053122 -0.42885775  0.1368165 ]
 [ 0.          0.         -1.08079798  2.01973547]
 [ 0.          0.          0.          0.45223238]]


In [28]:
np.matmul(Q,R)

array([[ 0.34 ,  0.4  ,  0.3  ,  0.9  ],
       [ 0.45 ,  0.25 ,  0.98 ,  0.46 ],
       [ 0.923,  0.34 ,  3.   , -2.   ],
       [ 0.34 , -0.45 ,  0.1  ,  0.55 ]])

In [29]:
A

array([[ 0.34 ,  0.4  ,  0.3  ,  0.9  ],
       [ 0.45 ,  0.25 ,  0.98 ,  0.46 ],
       [ 0.923,  0.34 ,  3.   , -2.   ],
       [ 0.34 , -0.45 ,  0.1  ,  0.55 ]])

## Householder transformation

In [30]:
import numpy as np

In [33]:
def Householder(A):
    m,n = A.shape
    R = A
    Q = np.eye(m)

    for j in range(n):
        x = R[j:,j]
        e_1 = np.zeros(len(x))
        e_1[0] = 1
        v_k = np.sign(x[0])*nla.norm(x)*e_1+x
        v_k = v_k/nla.norm(v_k) # normalize the reflection vector

        # Form of Householder transformation is H = I - 2(vv^t)/(v^tv)
        # R[j:, :]H Will eliminate all subdiagonal elements
        # Hence R[j:, :]H = R[j:, :] - R[j:, :]*2(vv^t)/(v^tv)
        R[j:, :] = R[j:, :] - 2* np.outer(v_k, v_k).dot(R[j:, :])
        Q[:, j:] = Q[:, j:] - 2 * Q[:, j:].dot(np.outer(v_k, v_k))
    
    return(Q,R)

In [34]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
print(nla.cond(A))
Q,R=Householder(A)
print (Q)
print(R)

37.75729255859722
[[-0.29986176 -0.45548197  0.72189882  0.4260061 ]
 [-0.39687586 -0.16662497  0.24300203 -0.86929609]
 [-0.81403649 -0.07202495 -0.52451613  0.23883014]
 [-0.29986176  0.87154157  0.38038788  0.07617926]]
[[-1.13385581e+00 -3.60998282e-01 -2.95099251e+00  1.01071052e+00]
 [ 2.21424777e-17 -6.40531217e-01 -4.28857747e-01  1.36816497e-01]
 [-1.07170808e-16 -2.61264017e-17 -1.08079798e+00  2.01973547e+00]
 [-5.85795884e-17  1.07904415e-16  0.00000000e+00 -4.52232385e-01]]


In [35]:
np.transpose(Q)

array([[-0.29986176, -0.39687586, -0.81403649, -0.29986176],
       [-0.45548197, -0.16662497, -0.07202495,  0.87154157],
       [ 0.72189882,  0.24300203, -0.52451613,  0.38038788],
       [ 0.4260061 , -0.86929609,  0.23883014,  0.07617926]])

In [36]:
nla.inv(Q)

array([[-0.29986176, -0.39687586, -0.81403649, -0.29986176],
       [-0.45548197, -0.16662497, -0.07202495,  0.87154157],
       [ 0.72189882,  0.24300203, -0.52451613,  0.38038788],
       [ 0.4260061 , -0.86929609,  0.23883014,  0.07617926]])

In [37]:
R

array([[-1.13385581e+00, -3.60998282e-01, -2.95099251e+00,
         1.01071052e+00],
       [ 2.21424777e-17, -6.40531217e-01, -4.28857747e-01,
         1.36816497e-01],
       [-1.07170808e-16, -2.61264017e-17, -1.08079798e+00,
         2.01973547e+00],
       [-5.85795884e-17,  1.07904415e-16,  0.00000000e+00,
        -4.52232385e-01]])

In [38]:
np.matmul(Q,R)

array([[ 0.34 ,  0.4  ,  0.3  ,  0.9  ],
       [ 0.45 ,  0.25 ,  0.98 ,  0.46 ],
       [ 0.923,  0.34 ,  3.   , -2.   ],
       [ 0.34 , -0.45 ,  0.1  ,  0.55 ]])

## Givens Rotation

In [202]:
def rotate_vector(x,y):
    ''' 
    Given a vector with two element x and y 
    rotate and normalize the vector
    '''
    if y == 0.0: 
        return 1.0,0.0
    r = np.hypot(x,y) 
    return x/r, -y/r

In [203]:
def givens_rotation(A):
    """Given a matrix A output Q and R matrix via
       Givens rotation """
    m, n = np.shape(A)

    # Initialize orthogonal matrix Q and upper triangular matrix R
    Q = np.identity(m)
    R = A

    # Iterate over lower triangular matrix.
    (rows, cols) = np.tril_indices(m, -1, n) # Return the indices for the lower-triangle of an array
    for (row, col) in zip(rows, cols):

        if R[row, col] != 0:
            (c, s) = rotate_vector(R[col, col], R[row, col])

            G = np.identity(m)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s

            R = np.dot(G, R)
            Q = np.dot(Q, np.transpose(G))

    return (Q, R)

In [204]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
Q, R = givens_rotation(A_mat)
# A_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Q, R = givens_QR(A_mat)

In [205]:
np.matmul(Q,R)

array([[ 0.34 ,  0.4  ,  0.3  ,  0.9  ],
       [ 0.45 ,  0.25 ,  0.98 ,  0.46 ],
       [ 0.923,  0.34 ,  3.   , -2.   ],
       [ 0.34 , -0.45 ,  0.1  ,  0.55 ]])