In [4]:
import numpy as np

In [5]:
##### Problem 13: Sparse Matrix for MAF #####
class mafSparse(object):

    def __init__(self, data = []):
        self.data = data

    # Take a vector and transform it into compressed sparse row format
    def makeSparse(self):

        # Get the number of rows and columns
        r = self.data.shape[0]
        c = self.data.shape[1]

        # Set up empty arrays to hold MAFs of 1
        ptrs1 = [0]
        cols1 = []

        # Set up empty arrays to hold MAFs of 2
        ptrs2 = [0]
        cols2 = []

        for i in range(1,r+1):
            for j in range(1,c+1):
                if self.data[i-1,j-1]==1:
                    cols1.append(j-1)
                elif self.data[i-1,j-1]==2:
                    cols2.append(j-1)
            ptrs1.append(len(cols1))
            ptrs2.append(len(cols2))

        # Append the total number of non-zero elements (convention)
        ptrs1.append(len(cols1))
        ptrs2.append(len(cols2))

        return [ptrs1, cols1], [ptrs2, cols2], [r,c]

    # Function to multiply the sparse matrix generated by makeSparse by a vector
    def multiply(self, ptrs1, cols1, ptrs2, cols2, r, c, vector):
        result = []

        # If the vector doesn't have same dimensions as matrix
        # Return error (note c is 1-indexed)
        if len(vector)!=c:
            return ValueError("Vector length must equal number of columns in matrix.")
        else:
            # Loop through each row of the csr matrix
            for i in range(0,len(ptrs1)-2):

                # Get the number of 1s and 2s in the row
                n1 = ptrs1[i+1]-ptrs1[i]
                n2 = ptrs2[i+1]-ptrs2[i]

                # Initialize a row of zeros width width = num cols
                row = np.zeros(shape=c)

                # Add in non-zero values
                if n1>0:
                    row[cols1[ptrs1[i]:ptrs1[i]+n1]] = 1
                if n2>0:
                    row[cols2[ptrs2[i]:ptrs2[i]+n2]] = 2

                # Initialize an element sum for the result
                elsum = 0
                # Multiply each row element by the vector element and sum them
                for j in range(0,len(row)):
                    elsum+=row[j]*vector[j]

                # Append the sum to our result vector
                result.append(elsum)

            # Return the result vector
            return result


# Sample testing code:

# A = np.matrix([[1,0,1],[1,1,1],[0,0,2]])
# print(A)
# test = mafSparse(A)
# [ptrs1, cols1], [ptrs2, cols2], [r,c] = test.makeSparse()
# test.multiply(ptrs1, cols1, ptrs2, cols2, r, c, [1,2,3])

In [6]:
A = np.matrix([[1,0,1],[1,1,1],[0,0,2]])
print(A)

[[1 0 1]
 [1 1 1]
 [0 0 2]]


In [7]:
test = mafSparse(A)
[ptrs1, cols1], [ptrs2, cols2], [r,c] = test.makeSparse()

In [8]:
test.multiply(ptrs1, cols1, ptrs2, cols2, r, c, [1,2,3])

[4.0, 6.0, 6.0]

In [10]:
test.makeSparse()

([[0, 2, 5, 5, 5], [0, 2, 0, 1, 2]], [[0, 0, 0, 1, 1], [2]], [3, 3])

In [11]:
A = np.matrix([[1,0,1,0,0],[1,0,2,0,1],[0,0,0,2,1]])
print(A)

[[1 0 1 0 0]
 [1 0 2 0 1]
 [0 0 0 2 1]]


In [12]:
test = mafSparse(A)
[ptrs1, cols1], [ptrs2, cols2], [r,c] = test.makeSparse()

In [14]:
test.multiply(ptrs1, cols1, ptrs2, cols2, r, c, [1,2,3,0,2])

[4.0, 9.0, 2.0]

In [88]:
import random
import numpy as np
def TravelSale(aMatrix):
    """
    Returns greedy travelling salesman path. Author: Lara Maleyeff

    :param  aList: list 
    :type   aList: aList
    
    Example input: 
    A= [[0, 1, 2, 3, 4], 
     [1, 0, 5, 6, 7],
     [2, 5, 0, 8, 9],
     [3, 6, 8, 0, 9],
     [4, 7, 9, 9, 0]]
    """
    # Initialize visited to an empty array - this will store our greedy optimal path
    visited = []
    # Check that matrix is 2x2 and symmetric with 0's on the diagonals
    if (len(aMatrix)!= len(aMatrix[0])):
        print("ERROR: Must input an n x n matrix!")
        return
    if (not np.allclose(np.matrix(aMatrix), np.matrix(aMatrix).transpose(), atol=1e-8)):
        print("ERROR: Matrix must be symmetric!")
        return
    for i in range(len(aMatrix)):
        if aMatrix[i][i] != 0:
            print("ERROR: Diagonals must be 0.")
            return
    
    # Start at random node
    currentNode = random.randint(0,len(aMatrix)-1)
    print("Starting node:" + str(currentNode))
    # Add starting node to visited list
    visited.append(currentNode)
    # While visited is not full
    while len(visited)<len(aMatrix):
        # Set minIndex and minValue to be infeasible values
        minIndex = -1
        minValue = 1000000000
        # Find the min valued node (not equal to 0 and not in visited)
        for i in range(0,len(aMatrix)):
            if i not in visited and aMatrix[currentNode][i]!=0:
                if aMatrix[currentNode][i]<=minValue:
                    minIndex = i
                    minvalue = aMatrix[currentNode][i]
        # If there are no nodes that meet the above conditon - there are no paths.
        if (minIndex <0):
            print("No path found.")
            return
        # Set current node to minimum-valued node and append to visited
        currentNode = minIndex
        visited.append(currentNode)
    if (aMatrix[visited[len(visited)-1]][visited[0]]==0):
        print("Cannot return to starting node.")
        return
    visited.append(visited[0])
    # Once visited is full, print and return
    print(visited)
    return(visited)

In [89]:
A= [[0, 1, 2, 3, 4], 
     [1, 0, 5, 6, 7],
     [2, 5, 0, 8, 9],
     [3, 6, 8, 0, 9],
     [4, 7, 9, 9, 0]]

In [90]:
TravelSale(A)

Starting node:1
[1, 4, 3, 2, 0, 1]


[1, 4, 3, 2, 0, 1]

In [86]:
A= [[0, 1, 2, 0, 4], 
     [1, 0, 5, 6, 7],
     [2, 5, 0, 0, 9],
     [0, 6, 0, 0, 9],
     [4, 7, 9, 9, 0]]

In [87]:
TravelSale(A)

Starting node:4
[4, 3, 1, 2, 0, 4]


[4, 3, 1, 2, 0, 4]