# Gaussian Elimintation

### Assuming matrices are in the traingular form

In [5]:
import numpy as np

In [4]:
def gaussElem_lower(A, b):
    """
    Given lower triangular matrix, solves the system of equations
    """
    
    n = len(b)
    x = [None]* n
    for j in range(n):
        if A[j,j] == 0:
            print('Matrix provided is singular')
            break
        x[j] = b[j]/A[j,j]
        for i in range(j+1, n):
            b[i] = b[i] - A[i,j]*x[j]
    return(x)
            
    
    
    

In [5]:
A = np.array([[4,0,0],[1,1,0],[-2,4,2]])
c = [8,4,2]

In [6]:
gaussElem_lower(A, c)

[2.0, 2.0, -1.0]

In [7]:
A = np.array([[4,0,0],[1,0,0],[-2,4,2]])
c = [8,4,2]
gaussElem_lower(A, c)

Matrix provided is singular


[2.0, None, None]

In [25]:
A.shape[1]

3

In [8]:
class SystemSolver():
    def __init__(self,data = []):
        # constructor - empty array
        self.data = data

    
    def LUFactorization(self, A):
        nrows = A.shape[0]
        ncols = A.shape[1]
        n = nrows
        if nrows == ncols:
            L = np.identity(n)
            U = A
            for i in range(n-1):
                for j in range(i+1,n):
                    L[j, i] = U[j,i]/float(U[i,i])
                    U[j,i:n] = U[j,i:n] - (float(L[j,i]) * U[i,i:n])
        return(L,U)
            
        
    def systemSolve(self, A, b):
        L,U = self.LUFactorization(A)
        
        # Forward substitution with L
        n = len(b)
        c = [None]* n
        for j in range(n):
            c[j] = b[j]/float(L[j,j])
            #print(c[j])
            for i in range(j+1, n):
                b[i] = b[i] - L[i,j]*c[j]

                
        # Backward substitution with U 
        x = [None]* n
        for j in range(n-1,-1,-1):
            x[j] = c[j]/float(U[j,j])
            for i in range(j):
                c[i] = c[i] - U[i,j]*x[j]
                
        return(x)
                
            
            
        
        


In [9]:
SS = SystemSolver()
A = np.array([[7,6,10],[3,8,7],[3,5,5]])
A = A.astype(float)
vec = [-7,-3,-2]
SS.systemSolve(A,vec)

[1.0, 1.0, -2.0]

In [10]:
L,U = SS.LUFactorization(A)

In [11]:
SS.systemSolve(U,[-7.0, 0.0, 1.0])

[1.0, 1.0, -2.0]

In [12]:
A = np.array([[7,6,10],[3,8,7],[3,5,5]])
vec = [-7,-3,-2]
A = A.astype(float)
SS.LUFactorization(A)

(array([[1.        , 0.        , 0.        ],
        [0.42857143, 1.        , 0.        ],
        [0.42857143, 0.44736842, 1.        ]]),
 array([[ 7.        ,  6.        , 10.        ],
        [ 0.        ,  5.42857143,  2.71428571],
        [ 0.        ,  0.        , -0.5       ]]))

In [13]:
SS.systemSolve(A,vec)

[-4.526315789473684, -2.5526315789473686, 4.0]

In [14]:
SS = SystemSolver()
A = np.array([[2,1,-2,3],[3,0,4,-2],[2,-1,1,5],[5,2,3,1]])
A = A.astype(float)
vec = [7,-1,13,5]
SS.systemSolve(A,vec)

[1.0, -1.0, -0.0, 2.0]

# Householder transformation

In [35]:
import numpy.linalg as nla

In [36]:
def Householder(A):
    m,n = A.shape
    R = A
    Q = np.eye(m)

    for j in range(n):
        x = R[j:,j]
        e_1 = np.zeros(len(x))
        e_1[0] = 1
        v_k = np.sign(x[0])*nla.norm(x)*e_1+x
        v_k = v_k/nla.norm(v_k) # normalize the reflection vector

        # Form of Householder transformation is H = I - 2(vv^t)/(v^tv)
        # R[j:, :]H Will eliminate all subdiagonal elements
        # Hence R[j:, :]H = R[j:, :] - R[j:, :]*2(vv^t)/(v^tv)
        R[j:, :] = R[j:, :] - 2* np.outer(v_k, v_k).dot(R[j:, :])
        Q[:, j:] = Q[:, j:] - 2 * Q[:, j:].dot(np.outer(v_k, v_k))
    
    return(Q,R)
    

In [37]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
print(nla.cond(A))
Q,R=Householder(A)
print (Q)
print(R)

37.75729255859722
[[-0.29986176 -0.45548197  0.72189882  0.4260061 ]
 [-0.39687586 -0.16662497  0.24300203 -0.86929609]
 [-0.81403649 -0.07202495 -0.52451613  0.23883014]
 [-0.29986176  0.87154157  0.38038788  0.07617926]]
[[-1.13385581e+00 -3.60998282e-01 -2.95099251e+00  1.01071052e+00]
 [ 2.21424777e-17 -6.40531217e-01 -4.28857747e-01  1.36816497e-01]
 [-1.07170808e-16 -2.61264017e-17 -1.08079798e+00  2.01973547e+00]
 [-5.85795884e-17  1.07904415e-16  0.00000000e+00 -4.52232385e-01]]


In [38]:
np.transpose(Q)

array([[-0.29986176, -0.39687586, -0.81403649, -0.29986176],
       [-0.45548197, -0.16662497, -0.07202495,  0.87154157],
       [ 0.72189882,  0.24300203, -0.52451613,  0.38038788],
       [ 0.4260061 , -0.86929609,  0.23883014,  0.07617926]])

In [39]:
nla.inv(Q)

array([[-0.29986176, -0.39687586, -0.81403649, -0.29986176],
       [-0.45548197, -0.16662497, -0.07202495,  0.87154157],
       [ 0.72189882,  0.24300203, -0.52451613,  0.38038788],
       [ 0.4260061 , -0.86929609,  0.23883014,  0.07617926]])

In [23]:
R

array([[-1.13385581e+00, -3.60998282e-01, -2.95099251e+00,
         1.01071052e+00],
       [ 2.21424777e-17, -6.40531217e-01, -4.28857747e-01,
         1.36816497e-01],
       [-1.07170808e-16, -2.61264017e-17, -1.08079798e+00,
         2.01973547e+00],
       [-5.85795884e-17,  1.07904415e-16,  0.00000000e+00,
        -4.52232385e-01]])

# Givens Rotation

In [24]:
def zeroing_givens_coeffs(x,z):
    ''' for the values x,z compute cos th, sin th 
        s.t. applying a Givens rotation G(cos th,sin th) 
             on 2 rows(or cols) with values x,z will
             maps x --> r and z --> 0'''
    if z == 0.0: # better:  abs(z) < np.finfo(np.double).eps
        return 1.0,0.0
    r = np.hypot(x,z) # C99 hypot is safe for under/overflow
    return x/r, -z/r

In [84]:
def rotate_vector(x,y):
    ''' 
    Given a vector with two element x and y 
    rotate and normalize the vector
    '''
    if y == 0.0: # better:  abs(z) < np.finfo(np.double).eps
        return 1.0,0.0
    r = np.hypot(x,y) # C99 hypot is safe for under/overflow
    return x/r, -y/r

In [85]:
rotate_vector(3,4)

(0.6, -0.8)

In [86]:
# GvL, pg. 216 .... Section 5.1.9
def givensRotation(c, s, A, r1, r2):
    ''' 
    Given a matrix A ,rows r1 and r2 and scalars s and c
    conduct a single Givens rotation
    '''
    givensT = np.array([[ c, -s],   # manually transposed 
                        [ s,  c]])
    A[[r1,r2],:] = np.dot(givensT, A[[r1,r2],:])

In [87]:
def givens_QR(A):
    m, n = A.shape
    Q = np.eye(m)
    R = A
    for i in range(n):
        for j in reversed(range(i+1, m)):  # m-1, m-2, ... c+2, c+1
            # in this row and the previous row, use zeroing givens to
            # place a zero in the lower row
            coeffs = rotate_vector(R[j-1, i], R[j,i])
            c = coeffs[0]
            s = coeffs[1]
            givensRotation(c, s, R[:, i:], j-1, j) 
            #print(R)
            # left_givensT(coeffs, A[r-1:r+1, c:], 0, 1)
            givensRotation(c, s, Q[:, i:], j-1, j)
            #print(Q)
    return Q,R

In [99]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
Q, R = givens_QR(A_mat)
A_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
Q, R = givens_QR(A_mat)

In [100]:
print(Q)
print(R)

[[ 0.12403473  0.49230769  0.86153846]
 [-0.99227788  0.06153846  0.10769231]
 [ 0.         -0.86824314  0.49613894]]
[[ 8  9 10]
 [ 0  0 -1]
 [ 0  0  0]]


In [79]:
import numpy.linalg as nla

In [101]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
A_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [102]:
Q = nla.qr(A_mat)[0]

In [103]:
print(-1 * np.transpose(Q))

[[ 0.12309149  0.49236596  0.86164044]
 [-0.90453403 -0.30151134  0.30151134]
 [-0.40824829  0.81649658 -0.40824829]]


In [104]:
print (nla.qr(A_mat)[1])

[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.12021634e-16]]


In [64]:
print (nla.qr(A_mat)[0])

[[-0.29986176 -0.45548197  0.72189882 -0.4260061 ]
 [-0.39687586 -0.16662497  0.24300203  0.86929609]
 [-0.81403649 -0.07202495 -0.52451613 -0.23883014]
 [-0.29986176  0.87154157  0.38038788 -0.07617926]]


In [51]:
np.matmul(Q, R)

array([[ 3.40000000e-01,  3.62460958e-01,  1.93490208e+00,
        -1.86590376e+00],
       [-1.08167879e+00, -2.37657607e-01, -2.66589287e+00,
         4.01792612e-01],
       [-9.94765808e-19, -1.48935380e-01,  4.67178599e-01,
        -1.19959518e+00],
       [-1.13568225e-17, -5.58644875e-01, -6.32159144e-01,
         5.67248666e-01]])

In [52]:
np.matmul(np.transpose(Q),Q)

array([[ 1.00000000e+00, -3.99494409e-02,  1.75387863e-01,
         9.21352622e-01],
       [-3.99494409e-02,  1.00000000e+00,  4.21410644e-01,
         1.28674942e-01],
       [ 1.75387863e-01,  4.21410644e-01,  1.00000000e+00,
        -2.77555756e-17],
       [ 9.21352622e-01,  1.28674942e-01, -2.77555756e-17,
         1.00000000e+00]])

In [37]:
for i in reversed(range(0, 9)):
    print(i)

8
7
6
5
4
3
2
1
0


In [57]:
def givens_rotation(A):
    """Perform QR decomposition of matrix A using Givens rotation."""
    m, n = np.shape(A)

    # Initialize orthogonal matrix Q and upper triangular matrix R.
    Q = np.identity(m)
    R = np.copy(A)

    # Iterate over lower triangular matrix.
    (rows, cols) = np.tril_indices(m, -1, n)
    for (row, col) in zip(rows, cols):

        # Compute Givens rotation matrix and
        # zero-out lower triangular matrix entries.
        if R[row, col] != 0:
            (c, s) = rotate_vector(R[col, col], R[row, col])

            G = np.identity(m)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s

            R = np.dot(G, R)
            Q = np.dot(Q, np.transpose(G))

    return (Q, R)

In [58]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
givens_rotation(A_mat)

(array([[ 0.09265586,  0.70853188, -0.34347701, -0.6094432 ],
        [-0.12263276,  0.46265689,  0.87767035,  0.02458789],
        [ 0.92074546,  0.18495337,  0.02154944,  0.34286392],
        [-0.35861384,  0.49972336, -0.33354748,  0.71443597]]),
 array([[ 0.70423761,  0.48083384,  2.63399166, -2.01174933],
        [ 0.78971434,  0.23708561,  1.27079575,  0.75544197],
        [ 0.18465347,  0.23944996,  0.78836742, -0.13195095],
        [ 0.36322549, -0.44255276,  0.94129853, -0.8299765 ]]))

In [ ]:
import numpy.linalg as nla