# Matrix Norm

In [115]:
import numpy as np

In [116]:
 b = np.array([[2,3,4],[5,7,9],[3,5,2]])

In [117]:
b

array([[2, 3, 4],
       [5, 7, 9],
       [3, 5, 2]])

In [118]:
np.linalg.norm(b,ord=np.inf)

21.0

In [119]:
np.linalg.norm(b,ord=1)

15.0

## Matrix Norm Identities

$||\gamma A|| = |\gamma| \times ||A||$ for any scalar $\gamma$

In [120]:
A = np.array([[-2,1,0],[5,9,9],[2,3,-2]])

In [121]:
np.linalg.norm(A,ord=2)

13.75151857513156

In [122]:
np.linalg.norm(2*A,ord=2)

27.50303715026312

$||A+ B|| \leq ||A|| + ||B||$

In [123]:
a = np.random.normal(loc=5, size=9)
A = a.reshape((3, 3))
b = np.random.normal(loc=3, size=9)
B = b.reshape((3, 3))

In [124]:
a_norm = np.linalg.norm(A,ord=2)
b_norm = np.linalg.norm(B,ord=2)
sum_norm = np.linalg.norm(A+B,ord=2)

In [125]:
print(a_norm + b_norm)
print(sum_norm)

23.575529975316854
23.042091677448013


$||AB|| \leq ||A|| \times ||B||$

In [126]:
prod_norm = np.linalg.norm(np.dot(A,B),ord=2)

In [127]:
print(a_norm * b_norm)
print(prod_norm)

122.80974492895979
119.34694579872708


$||Ax|| \leq ||A|| \times ||x||$ for any vector x

In [128]:
x = np.array([[3],[4],[9.2]])

In [129]:
vecProd_norm = np.linalg.norm(np.dot(A,x),ord=2)
x_norm = np.linalg.norm(x,ord=2)

In [130]:
print(a_norm * x_norm)
print(vecProd_norm)

165.49730238020138
153.3038285894252


# Gaussian Elimintation

### Assuming matrices are in the traingular form

In [111]:
import numpy as np

In [4]:
def gaussElem_lower(A, b):
    """
    Given lower triangular matrix, solves the system of equations
    """
    
    # get the length of vector b 
    n = len(b)
    # generate an empty vector with same length as b
   
    x = [None]*n
    
    # parse each row
    for i in range(n):
        # Check if the matrix is singular
        if A[i,i] == 0:
            print('The Matrix A is singular')
            break
        else:
            
        
        # if not perform forward substitution
        
        # populate x
        
    # return(x)    

In [5]:
A = np.array([[4,0,0],[1,1,0],[-2,4,2]])
c = [8,4,2]

In [6]:
gaussElem_lower(A, c)

[2.0, 2.0, -1.0]

In [7]:
A = np.array([[4,0,0],[1,0,0],[-2,4,2]])
c = [8,4,2]
gaussElem_lower(A, c)

Matrix provided is singular


[2.0, None, None]

In [25]:
A.shape[1]

3

In [184]:
def LUFactorization(A):
    nrows = A.shape[0]
    ncols = A.shape[1]
    n = nrows
    if nrows == ncols:
        L = np.identity(n)
        U = A
        for i in range(n-1):
            for j in range(i+1,n):
                L[j, i] = U[j,i]/U[i,i]
                U[j,i:n] = U[j,i:n] - (L[j,i] * U[i,i:n])
    return(L,U)
            
        
def systemSolve(A, b):
    L,U = LUFactorization(A)
        
    # Forward substitution with L
    n = len(b)
    c = [None]* n
    for j in range(n):
        c[j] = b[j]/float(L[j,j])
        #print(c[j])
        for i in range(j+1, n):
            b[i] = b[i] - L[i,j]*c[j]

                
    # Backward substitution with U 
    x = [None]* n
    for j in range(n-1,-1,-1):
        x[j] = c[j]/float(U[j,j])
        for i in range(j):
            c[i] = c[i] - U[i,j]*x[j]
                
    return(x)

In [185]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
L,U = LUFactorization(A)
print(L)
print(U)

[[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]
[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]


In [186]:
A = np.array([[2,1,-2,3],[3,0,4,-2],[2,-1,1,5],[5,2,3,1]])
A = A.astype(float)
vec = [7,-1,13,5]
systemSolve(A,vec)

[1.0, -1.0, -0.0, 2.0]